# server config
server:
  port: 5009
  servlet:
    context-path: /WeBASE-Data-Collect

# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webasedatacollect?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: "defaultAccount"
    password: "defaultPassword"
  servlet:
    multipart:
      max-request-size: 30MB # request max size
      max-file-size: 20MB # single file size

# constants
constant:
  ## front http request
  httpTimeOut: 5000
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 30000
  ## group update
  resetGroupListCycle: 300000
  groupInvalidGrayscaleValue: 1m    # y:year, M:month, d:day of month, h:hour, m:minute, n:forever valid
  ## data pull
  startBlockNumber: 0
  crawlBatchUnit: 50
  dataPullTaskFixedDelay: 10000
  ## data parser
  dataParserTaskFixedDelay: 10000
  ## stat txn daily
  statTxnDailyTaskFixedDelay: 60000

# executor config for pulling data
executor:
  corePoolSize: 50
  maxPoolSize: 100
  queueSize: 50
  threadNamePrefix: "custom-async-"

# mybatis config
mybatis:
  typeAliasesPackage: com.webank.webase.data.collect
  mapperLocations: classpath:mapper/*.xml
 
# log config
logging:
  config: classpath:log/log4j2.xml
  level:
    com.webank.webase.data.collect: info
